//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureCat.Patterns.DataElasticity.SQLAzure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataElasticityEntities : DbContext
    {
        public DataElasticityEntities()
            : base("name=DataElasticityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Database> Databases { get; set; }
        public DbSet<Server> Servers { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<ShardMap> ShardMaps { get; set; }
        public DbSet<ShardSetConfig> ShardSetConfigs { get; set; }
        public DbSet<ShardSetConfigSetting> ShardSetConfigSettings { get; set; }
        public DbSet<ShardSet> ShardSets { get; set; }
        public DbSet<RangeShard> RangeShards { get; set; }
        public DbSet<Shard> Shards { get; set; }
    }
}
