//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureCat.Patterns.DataElasticity.SQLAzure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Database
    {
        public Database()
        {
            this.RangeShards = new HashSet<RangeShard>();
            this.Shards = new HashSet<Shard>();
        }
    
        public int DatabaseID { get; set; }
        public string DatabaseName { get; set; }
        public int ServerID { get; set; }
    
        public virtual Server Server { get; set; }
        public virtual ICollection<RangeShard> RangeShards { get; set; }
        public virtual ICollection<Shard> Shards { get; set; }
    }
}
