//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureCat.Patterns.DataElasticity.SQLAzure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Version { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ShardPrefix { get; set; }
        public string AdminUserName { get; set; }
        public byte[] AdminUserPassword { get; set; }
        public string ShardUserName { get; set; }
        public byte[] ShardUserPassword { get; set; }
    }
}
