//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureCat.Patterns.DataElasticity.SQLAzure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShardMap
    {
        public ShardMap()
        {
            this.ShardSetConfigs = new HashSet<ShardSetConfig>();
            this.RangeShards = new HashSet<RangeShard>();
        }
    
        public int ShardMapID { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ShardSetConfig> ShardSetConfigs { get; set; }
        public virtual ICollection<RangeShard> RangeShards { get; set; }
    }
}
