//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureCat.Patterns.DataElasticity.SQLAzure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShardSet
    {
        public ShardSet()
        {
            this.ShardSetConfigs = new HashSet<ShardSetConfig>();
            this.Servers = new HashSet<Server>();
            this.Shards = new HashSet<Shard>();
        }
    
        public int ShardSetID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CurrentShardMapID { get; set; }
    
        public virtual ICollection<ShardSetConfig> ShardSetConfigs { get; set; }
        public virtual ICollection<Server> Servers { get; set; }
        public virtual ICollection<Shard> Shards { get; set; }
    }
}
