//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AzureCat.Patterns.DataElasticity.SQLAzure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShardSetConfigSetting
    {
        public int ShardSetConfigSettingID { get; set; }
        public int ShardSetConfigID { get; set; }
        public string SettingKey { get; set; }
        public string SettingValue { get; set; }
    
        public virtual ShardSetConfig ShardSetConfig { get; set; }
    }
}
